-- Migration: Add Database Indexes on Foreign Key Columns
-- Date: 2026-03-18
-- Author: @dev (Dex)
-- Status: SUPERSEDED — indexes já aplicados via migrations posteriores com schema correto
--
-- NOTA: Este arquivo foi escrito antes do schema ser finalizado.
-- Os indexes planejados aqui foram aplicados corretamente via outras migrations,
-- usando os nomes reais de tabela/coluna do banco:
--   - `company_id` → `user_id` (identificador de tenant real no schema)
--   - `transactions` → `finance_records` (nome real da tabela financeira)
--   - `scheduled_at` → `appointment_time` (nome real da coluna em appointments)
--
-- Equivalências confirmadas via pg_indexes (26 Mar 2026):
--   idx_clients_company_id         → idx_clients_user_id             ✅
--   idx_appointments_company_sched → idx_appointments_user_date       ✅
--   idx_appointments_client_id     → idx_appointments_client_id       ✅ (exato)
--   idx_transactions_company_creat → idx_finance_records_user_created ✅
--   idx_public_bookings_business_id→ idx_public_bookings_business_id  ✅ (exato)
--
-- NÃO APLICAR — causaria erro ("column company_id does not exist").
-- US-030 encerrada como DONE em 26 Mar 2026.